/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iitb.civil.tse.gui.toolBar;

import edu.iitb.civil.tse.gui.panel.opengl.Point3D;
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author dtripathy10
 */
public class StatusBar extends javax.swing.JPanel {

    private final Border blackline;

    /**
     * Creates new form StatusBar
     */
    public StatusBar() {
        initComponents();
         blackline = BorderFactory.createLineBorder(Color.GRAY);
        this.setBorder(blackline);
        //this.setBorder(raisedbevel);
    }

    public void setMessage(String string) {
       jLabel9.setText(string + "  selected ......");
    }

    public void setCordinate(Point3D point) {
        if(point ==null) {
            //do nothing
            return;
        }
        DecimalFormat df = new DecimalFormat("#.##");
        jLabel2.setText(df.format(point.getX()));
        jLabel4.setText(df.format(point.getY()));
        jLabel6.setText(df.format(point.getZ()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jLabel9 = new javax.swing.JLabel();

        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jToolBar1.setRollover(true);

        jLabel1.setText("X:  ");
        jToolBar1.add(jLabel1);

        jLabel2.setText("123.4");
        jToolBar1.add(jLabel2);
        jToolBar1.add(jSeparator1);

        jLabel3.setText("Y:   ");
        jToolBar1.add(jLabel3);

        jLabel4.setText("123.5");
        jToolBar1.add(jLabel4);
        jToolBar1.add(jSeparator2);

        jLabel5.setText("Z:   ");
        jToolBar1.add(jLabel5);

        jLabel6.setText("0.0");
        jToolBar1.add(jLabel6);
        jToolBar1.add(jSeparator3);

        jLabel8.setText("                                                                   ");
        jToolBar1.add(jLabel8);
        jToolBar1.add(jSeparator5);

        jLabel9.setText("Nothing  Selected......");
        jToolBar1.add(jLabel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
